<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use App\Models\Company;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaultCompany = Company::where('is_default', true)->first() ?? Company::first();
        $companyId = $defaultCompany ? $defaultCompany->id : null;

        $customers = [
            [
                'code'            => 'CST-01',
                'name'            => 'Raj Traders',
                'customer_type'   => 'Wholesaler',
                'contact_person'  => 'Rajendra Gehlot',
                'phone'           => '9829012345',
                'email'           => 'rajtraders.sojat@gmail.com',
                'gstin'           => '08AABCR1234F1Z5',
                'pan'             => 'AABCR1234F',
                'address'         => 'Shop No. 12-14, Krishi Mandi Complex, Pali Road',
                'city'            => 'Sojat',
                'state'           => 'Rajasthan',
                'pincode'         => '306104',
                'credit_limit'    => 500000.00,
                'payment_terms'   => '30 Days',
                'opening_balance' => 24500.00,
                'current_balance' => 24500.00,
                'bank_name'       => 'State Bank of India',
                'bank_account_no' => '31284567901',
                'bank_ifsc'       => 'SBIN0031123',
                'bank_branch'     => 'Krishi Mandi Branch, Sojat',
                'company_id'      => $companyId,
                'status'          => 'active',
                'notes'           => 'Long-standing regional mehndi wholesale partner. Prompt settlement record.',
            ],
            [
                'code'            => 'CST-02',
                'name'            => 'Marwar Herbal Distributors',
                'customer_type'   => 'Distributor',
                'contact_person'  => 'Sunil Sankhla',
                'phone'           => '9414123890',
                'email'           => 'sales@marwarherbal.in',
                'gstin'           => '08AADCM4567G1Z8',
                'pan'             => 'AADCM4567G',
                'address'         => 'A-24, Heavy Industrial Area, Phase II',
                'city'            => 'Jodhpur',
                'state'           => 'Rajasthan',
                'pincode'         => '342003',
                'credit_limit'    => 1000000.00,
                'payment_terms'   => '45 Days',
                'opening_balance' => 142800.00,
                'current_balance' => 142800.00,
                'bank_name'       => 'HDFC Bank',
                'bank_account_no' => '50200045612345',
                'bank_ifsc'       => 'HDFC0000215',
                'bank_branch'     => 'Industrial Area Jodhpur',
                'company_id'      => $companyId,
                'status'          => 'active',
                'notes'           => 'Distributes pure henna cone powder & herbal extracts across Western Rajasthan.',
            ],
            [
                'code'            => 'CST-03',
                'name'            => 'Global Henna Exports LLP',
                'customer_type'   => 'Exporter',
                'contact_person'  => 'Vikram Singhania',
                'phone'           => '9820098765',
                'email'           => 'procurement@globalhennaexports.com',
                'gstin'           => '27AAECG9876H1Z2',
                'pan'             => 'AAECG9876H',
                'address'         => 'Unit 502, B-Wing, Express Trade Towers, Bandra Kurla Complex',
                'city'            => 'Mumbai',
                'state'           => 'Maharashtra',
                'pincode'         => '400051',
                'credit_limit'    => 2500000.00,
                'payment_terms'   => '60 Days',
                'opening_balance' => 380000.00,
                'current_balance' => 380000.00,
                'bank_name'       => 'ICICI Bank',
                'bank_account_no' => '000405012987',
                'bank_ifsc'       => 'ICIC0000004',
                'bank_branch'     => 'BKC Corporate Branch, Mumbai',
                'company_id'      => $companyId,
                'status'          => 'active',
                'notes'           => 'Major export buyer for sterilized henna powder and Senna leaves for Middle-East markets.',
            ],
            [
                'code'            => 'CST-04',
                'name'            => 'Jaipur Ayurvedic Remedies',
                'customer_type'   => 'Direct Client',
                'contact_person'  => 'Dr. Manish Sharma',
                'phone'           => '9828114477',
                'email'           => 'orders@jaipurayurvedic.com',
                'gstin'           => '08AAFCA2345K1Z3',
                'pan'             => 'AAFCA2345K',
                'address'         => '108, Johari Bazaar, Pink City',
                'city'            => 'Jaipur',
                'state'           => 'Rajasthan',
                'pincode'         => '302003',
                'credit_limit'    => 400000.00,
                'payment_terms'   => '30 Days',
                'opening_balance' => 52000.00,
                'current_balance' => 52000.00,
                'bank_name'       => 'Bank of Baroda',
                'bank_account_no' => '21450200003489',
                'bank_ifsc'       => 'BARB0JOHARI',
                'bank_branch'     => 'Johari Bazaar, Jaipur',
                'company_id'      => $companyId,
                'status'          => 'active',
                'notes'           => 'Institutional buyer for Amla, Shikakai, Bhringraj and Henna raw formulations.',
            ],
            [
                'code'            => 'CST-05',
                'name'            => 'Vedic Beauty Care & Cosmetics',
                'customer_type'   => 'Distributor',
                'contact_person'  => 'Amitabh Verma',
                'phone'           => '9811223344',
                'email'           => 'vedicbeauty.delhi@gmail.com',
                'gstin'           => '07AABCV8765L1Z9',
                'pan'             => 'AABCV8765L',
                'address'         => 'D-42, Okhla Industrial Area Phase-1',
                'city'            => 'New Delhi',
                'state'           => 'Delhi',
                'pincode'         => '110020',
                'credit_limit'    => 800000.00,
                'payment_terms'   => '30 Days',
                'opening_balance' => 96500.00,
                'current_balance' => 96500.00,
                'bank_name'       => 'Axis Bank',
                'bank_account_no' => '918020034567891',
                'bank_ifsc'       => 'UTIB0000142',
                'bank_branch'     => 'Okhla Phase-1, New Delhi',
                'company_id'      => $companyId,
                'status'          => 'active',
                'notes'           => 'Distributes salon-grade hair packs, herbal henna pouches and natural hair colors.',
            ],
            [
                'code'            => 'CST-06',
                'name'            => 'Shree Ram Mandi Retailers',
                'customer_type'   => 'Retailer',
                'contact_person'  => 'Kanhaiyalal Prajapat',
                'phone'           => '9783456789',
                'email'           => 'shreerammandi@gmail.com',
                'gstin'           => '08AABCS9988M1Z4',
                'pan'             => 'AABCS9988M',
                'address'         => 'Main Bazaar, Near Clock Tower',
                'city'            => 'Pali',
                'state'           => 'Rajasthan',
                'pincode'         => '306401',
                'credit_limit'    => 150000.00,
                'payment_terms'   => '15 Days',
                'opening_balance' => 0.00,
                'current_balance' => 0.00,
                'bank_name'       => 'Punjab National Bank',
                'bank_account_no' => '0342002100098765',
                'bank_ifsc'       => 'PUNB0034200',
                'bank_branch'     => 'Pali City Branch',
                'company_id'      => $companyId,
                'status'          => 'active',
                'notes'           => 'Local retail counters & kirana store distribution network in Pali district.',
            ],
        ];

        foreach ($customers as $data) {
            Customer::updateOrCreate(
                ['code' => $data['code']],
                $data
            );
        }
    }
}
