<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class WhatsAppSetting extends Model
{
    use HasFactory;

    protected $table = 'whatsapp_settings';

    protected $fillable = [
        'company_id',
        'provider',
        'phone_number_id',
        'waba_id',
        'access_token',
        'display_phone_number',
        'webhook_verify_token',
        'is_enabled',
        'sandbox_mode',
        'monthly_quota',
        'credits_used',
        'auto_send_invoice',
        'auto_send_order',
        'auto_send_dispatch',
        'auto_send_receipt',
        'auto_send_due_reminder',
        'invoice_template',
        'order_template',
        'dispatch_template',
        'receipt_template',
        'due_reminder_template',
    ];

    protected $casts = [
        'is_enabled'             => 'boolean',
        'sandbox_mode'           => 'boolean',
        'auto_send_invoice'      => 'boolean',
        'auto_send_order'        => 'boolean',
        'auto_send_dispatch'     => 'boolean',
        'auto_send_receipt'      => 'boolean',
        'auto_send_due_reminder' => 'boolean',
        'monthly_quota'          => 'integer',
        'credits_used'           => 'integer',
    ];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Default message template strings.
     */
    public static function defaultTemplates(): array
    {
        return [
            'invoice' => "Namaste {{customer_name}},\n\nYour Tax Invoice *{{invoice_no}}* of amount *{{amount}}* has been generated by *{{company_name}}* on {{date}}.\n\nThank you for choosing Vikas Udhyog for your herbal products needs!\n\n_For any queries, reply to this WhatsApp message._",
            'order' => "Hello {{customer_name}},\n\nYour Order *{{order_no}}* has been confirmed by *{{company_name}}*.\nItems: {{items_summary}}\nExpected Dispatch: {{delivery_date}}.\n\nThank you for partnering with us!",
            'dispatch' => "Greetings {{customer_name}}!\n\nConsignment for Order *{{order_no}}* has been dispatched from our Sojat Plant.\nTransporter: *{{transporter}}*\nVehicle No: *{{vehicle_no}}*\nBilty / LR No: *{{bilty_no}}*\nDriver Contact: {{driver_phone}}.\n\nBest regards, Vikas Udhyog Sojat.",
            'receipt' => "Dear {{party_name}},\n\nWe acknowledge receipt of payment *{{amount}}* via {{payment_mode}} (Ref: {{ref_no}}) against Voucher *{{voucher_no}}*.\nCurrent outstanding balance: *{{balance}}*.\n\nThank you, *{{company_name}}*.",
            'due_reminder' => "Dear {{customer_name}},\n\nThis is a friendly reminder that an outstanding payment of *{{due_amount}}* is pending with *{{company_name}}*.\nDue Date: {{due_date}}.\n\nKindly remit payment via UPI: *{{bank_upi}}* or Bank Transfer.\nThank you for your cooperation."
        ];
    }

    /**
     * Retrieve the current active settings for a company or global default.
     */
    public static function getEffectiveSettings(?int $companyId = null): self
    {
        $query = static::query();
        if ($companyId) {
            $query->where('company_id', $companyId);
        }

        $setting = $query->first();

        if (!$setting) {
            $defaults = static::defaultTemplates();
            $setting = static::create([
                'company_id'             => $companyId,
                'provider'               => 'meta_cloud_api',
                'phone_number_id'        => '104859201948271',
                'waba_id'                => '109284729104857',
                'access_token'           => 'EAAG...SAMPLE_TOKEN...Z3B',
                'display_phone_number'   => '+91 98290 12345',
                'webhook_verify_token'   => 'vu_wa_verify_token_2026',
                'is_enabled'             => true,
                'sandbox_mode'           => true,
                'monthly_quota'          => 5000,
                'credits_used'           => 4825,
                'auto_send_invoice'      => true,
                'auto_send_order'        => true,
                'auto_send_dispatch'     => true,
                'auto_send_receipt'      => true,
                'auto_send_due_reminder' => false,
                'invoice_template'       => $defaults['invoice'],
                'order_template'         => $defaults['order'],
                'dispatch_template'      => $defaults['dispatch'],
                'receipt_template'       => $defaults['receipt'],
                'due_reminder_template'  => $defaults['due_reminder'],
            ]);
        }

        return $setting;
    }
}
